<div style="width: 320px; margin: 0 auto;">
   <h3><i class="fa fa-random"></i> LeadTrust.io Agent Login</h3>
   <? if (!empty($error)): ?>
      <div class="alert alert-error">
         <b>Error!</b> <?= $error ?>
      </div>
   <? elseif (!empty($info)): ?>
      <div class="alert alert-info">
         <b>Info.</b> <?= $info ?>
      </div>
   <? endif; ?>
   <form class="well" method="POST">
      <div class="form-group">
      <label>Agent ID</label>
         <input type="text" name="username" class="form-control" <? if (!empty($username)): ?> value="<?= $username ?>" <? endif; ?>>
      </div>
      <div class="form-group">
         <label>Password</label>
         <input type="password" name="password" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary btn-block">Login</button>
      
      <!-- <p>All information is logged and recorded based on our agent agreement</p> -->
   </form>
</div>
